[package]
name = "roguelite"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.3", default-features = false }
image = { version = "*", default-features = false, features = ["webp"] }
